// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture3D<float4> Forward;
Texture3D<float4> Right;
Texture3D<float4> Up;

RWTexture3D<float4> Result;

[numthreads(4, 4, 4)]
void CSMain (uint3 id : SV_DispatchThreadID) {
	float4 r = Right[id];
	float4 u = Up[id];
	float4 f = Forward[id];

	Result[id] = r.w * float4(r.xyz, 1) + u.w * float4(u.xyz, 1) + f.w * float4(f.xyz, 1);
}
